In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [4]:
df= pd.read_csv('Capstone_dataset/flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2652,4 BHK Flat in Shankar Vihar,https://www.99acres.com/4-bhk-bedroom-apartmen...,Dlf City,2.02 Crore,"₹ 8,080/sq.ft.",Super Built up area 2500(232.26 sq.m.),4 Bedrooms,3 Bathrooms,1 Balcony,NaN,"Shankar Vihar, Gurgaon, Haryana",2nd of 8 Floors,NaN,0 to 1 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Dr. ...",One of the best places to live in gurgaon. Has...,[],NaN,"['Environment4.5 out of 5', 'Safety5 out of 5'...",H69048128
2562,2 BHK Flat in Sector 104 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Godrej Summit3.7 ★,82 Lac,"₹ 9,854/sq.ft.",Carpet area: 77.31,2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 104 Gurgaon, Gurgaon, Haryana",12nd of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",Unleash your creativity and design your dream ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ...",Z68982730
26,2 BHK Flat in Sector 36 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,The Serenas,42 Lac,"₹ 7,910/sq.ft.",Carpet area: 531 (49.33 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sohna Sector 36, Sector 36 Gurgaon, Gurgaon, H...",3rd of 3 Floors,NaN,undefined,NaN,Best in class property available at sector 36 ...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN,E68804110
1409,4 BHK Flat in Sector 85 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Orris Aster Court Premier,1.73 Crore,"₹ 6,757/sq.ft.",Super Built up area 2560(237.83 sq.m.)Built Up...,4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,"652, Sector 85 Gurgaon, Gurgaon, Haryana",8th of 12 Floors,East,1 to 5 Year Old,"['Propose Metro Station', 'SS Omnia Mall', 'Na...",This lovely 4 bhk apartment/flat in sector 85 ...,NaN,"['Swimming Pool', 'Fitness Centre / GYM']","['Environment5 out of 5', 'Lifestyle5 out of 5...",X69344002
1526,2 BHK Flat in Sector 85 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,SS The Leaf3.8 ★,1.17 Crore,"₹ 7,001/sq.ft.",Super Built up area 1671(155.24 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sector 85 Gurgaon, Gurgaon, Haryana",11st of 26 Floors,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",This 2 bhk apartment is available for sale in ...,"['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou...",C70084858

In [5]:
df.shape

(3009, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3009 entries, 0 to 3008
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3009 non-null   object
 1   link             3009 non-null   object
 2   society          3008 non-null   object
 3   price            3008 non-null   object
 4   area             2997 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 470.3+ KB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                 1
area                 12
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1314
address               6
floorNum              2
facing              881
agePossession         1
nearbyLocations      95
description           0
furnishDetails      805
features            414
rating              332
property_id           0
dtype: int64

In [9]:
df.drop(columns=['link'],inplace=True)

In [10]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [11]:
## Rename col "area"
df.rename(columns={'area':'price_per_sqft'}, inplace=True)

In [12]:
## preprocessing Society col

print(df['society'].value_counts())
print(df['society'].value_counts().shape)  ## 637 unique socities

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Gems                                     32
Smart World Orchard                                  32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
La Vida by Tata Housing                              28
Godrej Nature Plus                                   27
Signature Global Solera3.7 ★                         27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
Eldeco Accolade3.8 ★                                 24
Experion The Heartsong3.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
DLF New Town Heights 13.9 ★                          24
Bestech Park View Residency3.9 ★                     23
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
Tata Primanti4.1 ★                                   22
M3M Heights                                          22
Sare Crescent Parc3.5 ★                              21
ROF Ananda                                           21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
ATS Tourmaline3.9 ★                                  18
CHD Avenue 713.6 ★                                   18
Supertech Araville                                   18
Mapsko Mount Ville4.1 ★                              18
Indiabulls Centrum Park3.7 ★                         18
Ambience Creacions                                   18
Sobha City                                           18
Conscient Heritage Max4.3 ★                          17
Godrej Summit3.7 ★                                   17
M3M Golfestate4.4 ★                                  17
M3M Skywalk                                          17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             16
Bestech Park View Grand Spa4.3 ★                     16
HCBS Sports Ville3.6 ★                               16
M3M Merlin3.7 ★                                      16
Umang Monsoon Breeze                                 15
Ansal Heights 86                                     15
Godrej Oasis3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Ireo Skyon4.0 ★                                      14
DLF The Primus3.9 ★                                  14
Indiabulls Enigma                                    14
Ramsons Kshitij3.7 ★                                 14
The Close North4.0 ★                                 14
Umang Winter Hills3.9 ★                              14
Imperia The Esfera                                   14
Ireo Victory Valley4.1 ★                             14
MVN Athens3.7 ★                                      14
Corona Optus3.9 ★                                    14
Vatika The Seven Lamps3.8 ★                          14
Orchid Petals4.1 ★                                   14
Ireo The Corridors                                   13
Puri Emerald Bay3.7 ★                                13
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
DLF The Skycourt4.2 ★                                11
SBTL Caladium                                        11
M3M Soulitude                                        11
Adani M2K Oyster Grande3.9 ★                         11
TARC Maceo3.8 ★                                      11
Godrej Aria3.8 ★                                     11
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
Emaar MGF Palm Hills4.0 ★                            10
Breez Global Heights4.2 ★                            10
Pyramid Urban Homes 2                                10
Ramprastha The Edge Towers3.5 ★                      10
Signature Global Synera3.4 ★                         10
Breez Global Hill View                               10
Capital Residences 360                               10
Pivotal Devaan                                       10
ATS Kocoon                                           10
Godrej Air                                           10
DLF New Town Heights 24.0 ★                          10
Zara Aavaas                                          10
Puri Diplomatic Greens4.0 ★                          10
AIPL The Peaceful Homes3.9 ★                          9
Bestech Park View Sanskruti4.2 ★                      9
Parsvnath Green Ville3.9 ★                            9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
ILD Greens4.1 ★                                       9
Pareena Mi Casa                                       9
The Lions CGHS                                        8
Birla Navya                                           8
GLS Avenue 51                                         8
Tulip Ivory3.5 ★                                      8
Bestech Altura                                        8
Emaar Digihomes                                       8
Orris Aster Court Premier                             8
M3M Skycity                                           8
Vatika Lifestyle Homes3.8 ★                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
M3M Capital                                           8
Sare Crescent Parc Royal Greens Phase 1               7
Sare Green ParC Phase 3                               7
Signature Global City                                 7
Ansal Housing Highland Park                           7
AIPL Zen Residences                                   7
Trisara Our Homes 3                                   7
Assotech Blith                                        7
Ireo The Grand Arch4.0 ★                              7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Emaar Imperial Gardens3.8 ★                           7
Signature Andour Heights3.8 ★                         7
Orris Carnation Residency3.7 ★                        7
Mapsko Casa Bella3.8 ★                                7
Ashiana Mulberry                                      6
Shapoorji Pallonji Joyville Gurugram                  6
HSIIDC Sidco Aravali                                  6
M3M Sierra 68                                         6
BPTP Astaire Gardens3.7 ★                             6
Sidhartha NCR One Phase 14.2 ★                        6
Pioneer Araya3.8 ★                                    6
Pyramid Urban                                         6
Kiran Residency                                       6
DLF Regency Park 13.6 ★                               6
Bestech Park View Spa Next4.0 ★                       6
Mapsko Royale Ville3.7 ★                              6
Bestech Park View City4.1 ★                           6
Supertech Hues                                        6
Suncity Vatsal Valley                                 6
Hero Homes                                            6
Parsvnath Exotica3.7 ★                                6
Signature Global Park 4                               6
Signature The Roselia3.6 ★                            6
Signature Global City 63A                             6
Vatika Sovereign Park                                 5
Emaar MGF Emerald Estate3.8 ★                         5
Krisumi Waterfall Residences                          5
Pareena Laxmi Apartments3.6 ★                         5
ATS Marigold                                          5
Central Park Resorts4.4 ★                             5
Signature Global City 37D Ph 2                        5
Central Park Flower Valley Aqua Front Towers          5
Vatika City Homes3.9 ★                                5
Signature Global the Millennia                        5
M3M The Marina4.0 ★                                   5
Conscient Elevate                                     5
Green Court3.7 ★                                      5
Adani Brahma Samsara Vilasa                           5
Greenopolis                                           5
DLF Park Place4.1 ★                                   5
Ireo Uptown4.1 ★                                      5
Signature Global City 81                              5
Ashiana Anmol3.5 ★                                    5
Signature Global Grand IVA3.9 ★                       5
Silverglades The Melia                                5
Apna Enclave                                          5
Signature Global City 92                              5
Godrej Habitat                                        5
Pioneer Park3.8 ★                                     5
Essel Towers                                          5
Satya The Hermitage3.5 ★                              5
DLF Regency Park 24.0 ★                               5
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
Corona Gracieux                                       4
Sare Petioles                                         4
SS The Coralwood3.4 ★                                 4
Ramprastha Skyz                                       4
Railway Officers RPF Society                          4
Godrej Icon                                           4
Tulip Monsella                                        4
Emaar Palm Heights                                    4
Global Hill View                                      4
Orris Aster Court                                     4
Signature The Serenas                                 4
ILD Grand                                             4
Krrish Provence Estate                                4
Tata Gurgaon Gateway3.8 ★                             4
Ramprastha Primera                                    4
Prime Habitat                                         4
Unitech Vistas                                        4
DLF New Town Heights3.7 ★                             4
Godrej Frontier3.7 ★                                  4
Lotus Homz4.0 ★                                       4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Unitech Fresco3.8 ★                                   4
DLF Royalton Tower                                    3
Smriti Apartment                                      3
Mahindra Aura4.2 ★                                    3
SS Almeria                                            3
Brisk Lumbini Terrace Homes                           3
Shree Arihant Apartment                               3
Sukhshanti Apartment                                  3
Kendriya Vihar4.1 ★                                   3
Puri Diplomatic Greens3.9 ★                           3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Sunischit Apartments                                  3
Dhoot Time Residency4.0 ★                             3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Unitech Sunbreeze                                     3
Vatika Xpressions                                     3
Spaze Privy AT43.9 ★                                  3
Siddhartha Apartment                                  3
ATS Kocoon4.2 ★                                       3
Spaze Privy3.9 ★                                      3
Raheja Revanta                                        3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Essel Tower                                           3
Suncity Platinum Towers                               3
Guru Gram Haryana CGHS4.1 ★                           3
Piedmont Taksila heights3.6 ★                         3
Apex Our Homes                                        3
Pivotal Riddhi Siddhi                                 3
Krrish Florence Estate                                3
DLF Belvedere Towers3.8 ★                             3
Tulip Petals3.6 ★                                     3
Chintels Paradiso3.9 ★                                3
Ambience Lagoon3.9 ★                                  3
DLF Carlton Estate4.0 ★                               3
Paras Quartier                                        3
Unitech Heritage City                                 3
Sapphire Eighty Three                                 3
DLF The Grove                                         3
Tulip White3.5 ★                                      3
AIPL Club Residences                                  3
Vatika Independent Floors3.8 ★                        3
Deepak Minda                                          3
DLF The Arbour                                        3
Spaze Privvy The Address3.9 ★                         3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Shri Banke Bihari Society3.8 ★                        3
Maxworth City Residences                              3
The Roselia 2                                         3
Sidhartha NCR Greens4.3 ★                             3
AFNHB Jalvayu Vihar3.7 ★                              3
Bestech Park View City 23.9 ★                         3
Pyramid Elite                                         3
Satya Element One                                     3
Valley View Estate                                    3
Unitech Uniworld Gardens3.8 ★                         3
Adani Aangan Arcade                                   3
Shri Ram Apartments                                   3
Unitech The Residences3.7 ★                           3
Sare Green Parc                                       3
Raheja Atharva3.6 ★                                   3
Tulip Purple                                          3
Tulsiani Easy in Homes                                2
Landmark The Residency                                2
Vasant Appartments                                    2
Maruti Vihar                                          2
Sidhivinayak Apartments                               2
Bhagwati Sadan                                        2
Ambience Caitriona                                    2
Breeze Global Heights                                 2
Element One Service                                   2
Milan CGHS 9                                          2
Vipul World Floors                                    2
Apartment                                             2
Samaspurkunj                                          2
Residency Grand                                       2
Surendra Avenue 69                                    2
Silverglades Hightown Residences                      2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Mittal Surya Vihar                                    2
Suposhaa Smartworld Orchard                           2
Park Royal Apartment                                  2
The Close South3.9 ★                                  2
Elan The Presidential                                 2
M3M Latitude                                          2
Pioneer Urban Presidia                                2
Lavanya Apartments                                    2
om appartments                                        2
Ganga Apartment                                       2
Ashiana Anmol                                         2
Godrej Nature Plus Serenity                           2
Suncity Avenue 76                                     2
Supertech Hill Town                                   2
NBCC Heights3.9 ★                                     2
BPTP Pedestal                                         2
MRG World Ultimus                                     2
Unitech Uniworld Gardens 23.4 ★                       2
Mahindra Luminare4.0 ★                                2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
Green Campus CHS                                      2
Oriental Valley CHS                                   2
Puri The Aravallis                                    2
Aqua Front Towers                                     2
Sahara Grace                                          2
BPTP Freedom Park Life4.0 ★                           2
Housing Board Colony                                  2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
My Home                                               2
Ardee City3.8 ★                                       2
M3M Urbana                                            2
Today Callidora                                       2
Bestech Spa Signature                                 2
DLF The Icon3.7 ★                                     2
Ramprastha The Atrium3.4 ★                            2
Tulip Orange3.9 ★                                     2
Central Park 2 Bellevue                               2
Raheja Atlantis3.8 ★                                  2
Ansal API Esencia3.7 ★                                2
AWHO Shanti Vihar4.0 ★                                2
ROF Aalayas3.8 ★                                      2
M3M Sky Lofts                                         2
Signature Global The Millennia 3                      2
Orchid Island4.2 ★                                    2
Emaar MGF Palm Studios                                2
Suncity Heights3.7 ★                                  2
Ansal Heights3.2 ★                                    2
Mapsko Paradise3.9 ★                                  2
DLF The Crest3.6 ★                                    2
BPTP Mansions Park Prime                              2
Vatika Emilia Floors3.7 ★                             2
Tulip Violet                                          2
Tulip Leaf                                            2
Viridian The Plaza 106                                2
The Penthouses at the Hibiscus                        2
M3M Ikonic                                            2
Ramprastha City                                       2
Supertech Hilltown                                    2
Bestech Park View Sanskruti4.1 ★                      2
Emaar MGF The Enclave                                 2
Palam Vihar Society                                   2
Vatika INXT Floors                                    2
Vipul Belmonte3.9 ★                                   2
Professors Enclave CGHS                               2
Raheja Vanya                                          2
BPTP Amstoria3.8 ★                                    2
Suncity Avenue 1023.9 ★                               2
DLF The Belaire3.9 ★                                  2
SS Hibiscus                                           2
Paras Irene3.7 ★                                      2
lagoon apartment                                      2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Ramprasta AWHO                                        1
signature global rosellia                             1
CGHS Rail Vihar4.0 ★                                  1
The Cocoon                                            1
takshila heights sector 37 c                          1

In [13]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [14]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
emaar mgf emerald floors premier                 32
smart world orchard                              32
smart world gems                                 32
paras dews                                       31
dlf the ultima                                   31
m3m woodshire                                    30
dlf regal gardens                                30
shree vardhman flora                             29
la vida by tata housing                          28
signature global solera                          27
godrej nature plus                               27
emaar gurgaon greens                             25
bptp terra                                       25
eldeco accolade                                  24
experion the heartsong                           24
vatika gurgaon                                   24
bestech park view residency                      23
tata primanti                                    22
emaar palm gardens                               22
m3m heights                                      22
ats triumph                                      22
rof ananda                                       21
godrej                                           21
sare crescent parc                               21
experion windchants                              20
sare homes                                       19
antriksh heights                                 19
mapsko mount ville                               18
ats tourmaline                                   18
m3m skywalk                                      18
indiabulls centrum park                          18
chd avenue                                       18
sobha city                                       18
hcbs sports ville                                18
m3m golfestate                                   18
ambience creacions                               18
supertech araville                               18
godrej summit                                    17
conscient heritage max                           17
gls arawali homes                                17
m3m merlin                                       16
pareena coban residences                         16
bestech park view grand spa                      16
emaar mgf the palm drive                         15
ansal heights 86                                 15
umang monsoon breeze                             15
godrej oasis                                     15
ramsons kshitij                                  15
dlf the skycourt                                 15
dlf the primus                                   14
imperia the esfera                               14
corona optus                                     14
bestech park view ananda                         14
ireo skyon                                       14
umang winter hills                               14
ireo victory valley                              14
the close north                                  14
orchid petals                                    14
vatika the seven lamps                           14
indiabulls enigma                                14
mvn athens                                       14
puri emerald bay                                 13
central park flower valley                       13
puri diplomatic greens                           13
ats kocoon                                       13
ireo the corridors                               13
m3m soulitude                                    11
godrej aria                                      11
breez global heights                             11
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
raheja vedaanta                                  11
tarc maceo                                       11
dlf regency park                                 11
sbtl caladium                                    11
adani m2k oyster grande                          11
godrej air                                       10
pivotal devaan                                   10
zara aavaas                                      10
ramprastha the edge towers                       10
capital residences 360                           10
signature global synera                          10
ild greens                                       10
breez global hill view                           10
emaar mgf palm hills                             10
pyramid urban homes 2                            10
vatika city                                       9
microtek greenburg                                9
parsvnath green ville                             9
aipl the peaceful homes                           9
bestech park view city                            9
pareena mi casa                                   9
gls avenue 51                                     8
vatika lifestyle homes                            8
tulip ivory                                       8
m3m capital                                       8
bestech altura                                    8
ss                                                8
avl 36 gurgaon                                    8
birla navya                                       8
orris aster court premier                         8
m3m skycity                                       8
emaar digihomes                                   8
the lions cghs                                    8
ireo the grand arch                               7
signature global orchard avenue                   7
trisara our homes 3                               7
orris carnation residency                         7
sare crescent parc royal greens phase 1           7
sidhartha ncr one phase                           7
mapsko casa bella                                 7
aipl zen residences                               7
assotech blith                                    7
ashiana anmol                                     7
sare green parc phase 3                           7
emaar imperial gardens                            7
signature andour heights                          7
vipul lavanya                                     7
signature global city                             7
ansal housing highland park                       7
kiran residency                                   6
supertech hues                                    6
signature global city 63a                         6
mapsko royale ville                               6
signature global park 4                           6
signature the roselia                             6
pioneer araya                                     6
suncity vatsal valley                             6
hero homes                                        6
green court                                       6
parsvnath exotica                                 6
pyramid urban                                     6
bptp astaire gardens                              6
m3m sierra 68                                     6
hsiidc sidco aravali                              6
bestech park view spa next                        6
ashiana mulberry                                  6
vatika sovereign park                             5
essel towers                                      5
krisumi waterfall residences                      5
signature global city 37d ph 2                    5
ats marigold                                      5
conscient elevate                                 5
unitech fresco                                    5
godrej habitat                                    5
adani brahma samsara vilasa                       5
greenopolis                                       5
signature global grand iva                        5
vatika city homes                                 5
ireo uptown                                       5
dlf park place                                    5
pareena laxmi apartments                          5
emaar mgf emerald estate                          5
silverglades the melia                            5
pioneer park                                      5
signature global the millennia                    5
satya the hermitage                               5
central park flower valley aqua front towers      5
signature global city 92                          5
central park resorts                              5
unitech uniworld gardens                          5
m3m the marina                                    5
signature global city 81                          5
apna enclave                                      5
unitech vistas                                    4
ild grand                                         4
corona gracieux                                   4
sare petioles                                     4
global hill view                                  4
tulip monsella                                    4
railway officers rpf society                      4
ramprastha skyz                                   4
lotus homz                                        4
signature the serenas                             4
afnhb jalvayu vihar                               4
raheja navodaya                                   4
kendriya vihar                                    4
krrish provence estate                            4
orris aster court                                 4
essel tower                                       4
godrej icon                                       4
emaar palm heights                                4
ramprastha primera                                4
prime habitat                                     4
hsiidc sidco shivalik apartments                  4
dlf the arbour                                    4
ss the coralwood                                  4
tata gurgaon gateway                              4
godrej frontier                                   4
sidhartha ncr one                                 3
pivotal riddhi siddhi                             3
vatika independent floors                         3
satya element one                                 3
sapphire eighty three                             3
dlf royalton tower                                3
tulip white                                       3
pyramid elite                                     3
brisk lumbini terrace homes                       3
spaze privvy the address                          3
aipl club residences                              3
ambience lagoon                                   3
tulip purple                                      3
raheja sampada                                    3
dlf the grove                                     3
dlf carlton estate                                3
ss almeria                                        3
dlf belvedere towers                              3
sukhshanti apartment                              3
vatika xpressions                                 3
smriti apartment                                  3
chintels paradiso                                 3
shree arihant apartment                           3
adani aangan arcade                               3
dhoot time residency                              3
apex our homes                                    3
guru gram haryana cghs                            3
conscient habitat                                 3
bhagwati sadan                                    3
spaze privy                                       3
tulip lemon                                       3
suncity platinum towers                           3
spaze privy at                                    3
sunischit apartments                              3
siddhartha apartment                              3
deepak minda                                      3
shri banke bihari society                         3
piedmont taksila heights                          3
krrish florence estate                            3
sare green parc                                   3
unitech the residences                            3
whiteland blissville                              3
signature global solera 2                         3
sare green parc 2                                 3
unitech sunbreeze                                 3
paras quartier                                    3
raheja atharva                                    3
shri ram apartments                               3
the roselia 2                                     3
sidhartha ncr greens                              3
valley view estate                                3
mahindra aura                                     3
maxworth city residences                          3
tulip petals                                      3
raheja revanta                                    3
dlf express greens                                3
unitech heritage city                             3
maruti vihar                                      2
mrg world ultimus                                 2
samaspurkunj                                      2
om appartments                                    2
ardee city                                        2
jammu and kashmir bank employees cghs             2
mittal surya vihar                                2
mapsko paradise                                   2
suposhaa smartworld orchard                       2
landmark the residency                            2
dlf city                                          2
shapoorji pallonji joyville                       2
breeze global heights                             2
element one service                               2
sidhivinayak apartments                           2
ambience caitriona                                2
surendra avenue 69                                2
silverglades hightown residences                  2
park royal apartment                              2
milan cghs 9                                      2
vipul world floors                                2
apartment                                         2
lavanya apartments                                2
residency grand                                   2
ss residency                                      2
bptp pedestal                                     2
ramprastha city                                   2
vasant appartments                                2
shree shyam residency                             2
ansal api celebrity suites                        2
shyam apartment                                   2
ansal api esencia                                 2
awho shanti vihar                                 2
rof aalayas                                       2
raheja atlantis                                   2
housing board colony                              2
central park 2 bellevue                           2
tulip orange                                      2
m3m latitude                                      2
pioneer urban presidia                            2
today callidora                                   2
ramprastha the atrium                             2
aqua front towers                                 2
sahara grace                                      2
adani aangan galleria                             2
lagoon apartment                                  2
ganga apartment                                   2
godrej nature plus serenity                       2
suncity avenue 76                                 2
supertech hill town                               2
mahindra luminare                                 2
elan the presidential                             2
oriental valley chs                               2
emaar mgf emerald floors                          2
nbcc heights                                      2
suncity heights                                   2
puri the aravallis                                2
my home                                           2
the close south                                   2
bptp freedom park life                            2
cghs airport apartment                            2
palam vihar society                               2
m3m urbana                                        2
green campus chs                                  2
bestech spa signature                             2
ansal heights                                     2
vatika emilia floors                              2
emaar mgf palm studios                            2
orchid island                                     2
signature global the millennia 3                  2
m3m sky lofts                                     2
raheja vanya                                      2
tulip leaf                                        2
viridian the plaza 106                            2
ss hibiscus                                       2
vatika inxt floors                                2
bptp amstoria                                     2
dlf the icon                                      2
vipul belmonte                                    2
m3m ikonic                                        2
emaar mgf the enclave                             2
bptp mansions park prime                          2
the penthouses at the hibiscus                    2
dlf the crest                                     2
professors enclave cghs                           2
dlf the belaire                                   2
suncity avenue                                    2
paras irene                                       2
supertech hilltown                                2
tulsiani easy in homes                            2
spire woods now ananda by alpha corp              1
maa bhagwati residency                            1
parkwood westend                                  1
signature global infinity mall                    1
the cocoon                                        1
rk tower                                          1
ss radiance residency                             1
ramshanti cooperative society                     1
smart world one                                   1
sanskriti apartment                               1
elan mercado                                      1
bajrang apartments                                1
m3m the tree of life                              1
kashish manor one                                 1
the pearl apartmen                                1
sushant lok 1 builder floors                      1
m3m one key resiments                             1
godrej summit premia towers                       1
czar mahira homes 63a                             1
shri balaji apartment                             1
lig flat                                          1
imt view society                                  1
aardhya homesh                                    1
signature signum 95a                              1
abhinav group housing society                     1
m3m golf hills phase 1                            1
ashiyara 2                                        1
hanumanta apartment                               1
shyam sadan                                       1
micasa sec 68                                     1
krishna appartment                                1
godrej aria , sector 79 , gurgaon                 1
uphar lakshya homes                               1
chanderlok society                                1
ansal estella                                     1
laxmi apartment sector 99a gurgaon                1
sanskriti apartments                              1
vatika sovereign next sector-82 a gurgaon         1
professional society                              1
unitech harmony                                   1
.                                                 1
emaar mgf palm terraces select                    1

In [15]:
## preprocessing price col
print(df['price'].value_counts())
print(df['price'].value_counts().shape)  ## 440 unique prices

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
1.65 Crore          38
75 Lac              38
1.7 Crore           37
1.8 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
40 Lac              29
60 Lac              29
2.5 Crore           29
45 Lac              26
2.1 Crore           26
65 Lac              25
2.35 Crore          23
1.85 Crore          23
35 Lac              23
3 Crore             22
70 Lac              21
55 Lac              20
2.25 Crore          20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
2.45 Crore          14
2.15 Crore          14
3.4 Crore           14
92 Lac              13
2.7 Crore           13
82 Lac              13
78 Lac              13
1.32 Crore          13
3.25 Crore          13
38 Lac              13
1.95 Crore          12
42 Lac              12
2.8 Crore           12
1.42 Crore          12
5 Crore             12
Price on Request    11
88 Lac              11
32 Lac              11
1.08 Crore          11
25 Lac              11
28 Lac              10
1.12 Crore          10
26 Lac              10
2.55 Crore          10
1.78 Crore          10
87 Lac              10
1.28 Crore          10
1.68 Crore           9
2.05 Crore           9
3.45 Crore           9
4 Crore              9
1.72 Crore           9
22 Lac               9
99 Lac               9
2.85 Crore           9
36 Lac               9
20 Lac               8
1.54 Crore           8
1.76 Crore           8
98 Lac               8
6 Crore              8
1.18 Crore           8
6.5 Crore            8
4.25 Crore           8
1.26 Crore           8
2.75 Crore           8
3.2 Crore            8
48 Lac               8
86 Lac               8
27 Lac               8
56 Lac               8
1.99 Crore           7
79 Lac               7
46 Lac               7
72 Lac               7
2.9 Crore            7
1.19 Crore           7
1.27 Crore           7
3.3 Crore            7
39 Lac               7
3.7 Crore            7
1.02 Crore           7
1.36 Crore           7
97 Lac               7
1.29 Crore           7
1.49 Crore           6
37 Lac               6
1.01 Crore           6
1.07 Crore           6
96 Lac               6
5.5 Crore            6
1.51 Crore           6
1.34 Crore           6
43 Lac               6
1.13 Crore           6
4.1 Crore            6
71.5 Lac             6
3.65 Crore           6
54 Lac               6
3.05 Crore           6
1.39 Crore           6
1.14 Crore           6
3.35 Crore           6
1.59 Crore           6
21 Lac               6
1.16 Crore           6
3.9 Crore            6
2.95 Crore           6
1.98 Crore           6
1.62 Crore           5
1.83 Crore           5
68 Lac               5
1.92 Crore           5
64 Lac               5
4.5 Crore            5
93 Lac               5
1.44 Crore           5
24 Lac               5
1.69 Crore           5
1.91 Crore           5
1.43 Crore           5
1.17 Crore           5
2.22 Crore           5
1.82 Crore           5
1.79 Crore           5
2.78 Crore           5
2.29 Crore           5
49 Lac               5
1.33 Crore           5
2.12 Crore           5
1.93 Crore           5
1.24 Crore           5
66 Lac               5
6.75 Crore           5
3.75 Crore           5
29 Lac               5
1.47 Crore           5
58 Lac               4
89 Lac               4
1.23 Crore           4
6.15 Crore           4
67 Lac               4
5.9 Crore            4
62 Lac               4
7 Crore              4
4.85 Crore           4
5.25 Crore           4
1.37 Crore           4
73 Lac               4
36.5 Lac             4
33 Lac               4
1.64 Crore           4
3.6 Crore            4
4.3 Crore            4
1.22 Crore           4
31 Lac               4
1.66 Crore           4
3.1 Crore            4
74 Lac               4
41.5 Lac             4
28.5 Lac             4
2.09 Crore           4
1.71 Crore           4
1.73 Crore           4
1.58 Crore           4
1.31 Crore           4
3.95 Crore           4
1.77 Crore           4
1.52 Crore           4
1.48 Crore           4
5.6 Crore            4
47 Lac               3
2.08 Crore           3
69 Lac               3
94 Lac               3
2.01 Crore           3
1.57 Crore           3
1.88 Crore           3
84 Lac               3
83 Lac               3
64.5 Lac             3
2.51 Crore           3
51 Lac               3
5.8 Crore            3
1.63 Crore           3
4.2 Crore            3
72.5 Lac             3
1.09 Crore           3
4.8 Crore            3
2.28 Crore           3
3.49 Crore           3
91 Lac               3
1.21 Crore           3
2.36 Crore           3
34 Lac               3
1.67 Crore           3
3.8 Crore            3
2.03 Crore           3
1.04 Crore           3
3.15 Crore           3
3.85 Crore           3
2.33 Crore           3
2.79 Crore           3
1.41 Crore           3
52 Lac               3
2.24 Crore           3
4.75 Crore           3
41 Lac               2
2.41 Crore           2
4.26 Crore           2
14 Crore             2
2.02 Crore           2
2.91 Crore           2
27.75 Lac            2
52.56 Lac            2
4.55 Crore           2
11 Crore             2
7.5 Crore            2
27.1 Lac             2
2.04 Crore           2
25.5 Lac             2
5.7 Crore            2
2.58 Crore           2
2.14 Crore           2
56.2 Lac             2
31.5 Lac             2
3.55 Crore           2
98.5 Lac             2
87.5 Lac             2
59 Lac               2
88.5 Lac             2
71 Lac               2
4.7 Crore            2
4.45 Crore           2
3.29 Crore           2
1.56 Crore           2
2.99 Crore           2
2.26 Crore           2
2.13 Crore           2
2.17 Crore           2
8.5 Crore            2
8 Crore              2
1.46 Crore           2
53.5 Lac             2
2.52 Crore           2
2.23 Crore           2
6.2 Crore            2
4.49 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
1.87 Crore           2
77.5 Lac             2
53 Lac               2
2.87 Crore           2
2.57 Crore           2
5.2 Crore            2
99.5 Lac             1
3.83 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
2.98 Crore           1
66.99 Lac            1
2.48 Crore           1
89.5 Lac             1
2.21 Crore           1
97.04 Lac            1
3.23 Crore           1
94.5 Lac             1
82.5 Lac             1
3.99 Crore           1
9 Crore              1
2.44 Crore           1
7.9 Crore            1
6.02 Crore           1
29.8 Lac             1
61 Lac               1
54.8 Lac             1
3.98 Crore           1
2.54 Crore           1
15 Crore             1
39.5 Lac             1
4.02 Crore           1
7.8 Crore            1
1.97 Crore           1
price                1
3.87 Crore           1
4.95 Crore           1
5.31 Crore           1
5.4 Crore            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
95.75 Lac            1
3.46 Crore           1
3.19 Crore           1
3.67 Crore           1
8.25 Crore           1
4.63 Crore           1
4.4 Crore            1
29.5 Lac             1
68.85 Lac            1
98.88 Lac            1
3.78 Crore           1
37.5 Lac             1
2.69 Crore           1
4.78 Crore           1
3.63 Crore           1
80.5 Lac             1
68.5 Lac             1
85.5 Lac             1
93.75 Lac            1
94.25 Lac            1
4.79 Crore           1
31.75 Lac            1
55.5 Lac             1
2.37 Crore           1
23.5 Lac             1
27.5 Lac             1
2.82 Crore           1
54.99 Lac            1
7.15 Crore           1
35.5 Lac             1
10.75 Crore          1
4.94 Crore           1
1.06 Crore           1
2.11 Crore           1
5.75 Crore           1
6.1 Crore            1
8.35 Crore           1
81 Lac               1
26.1 Lac             1
9.14 Crore           1
20.5 Lac             1
17.5 Lac             1
24.5 Lac             1
10 Crore             1
29.99 Lac            1
79.9 Lac             1
23 Lac               1
71.2 Lac             1
11.25 Crore          1
6.3 Crore            1
5.49 Crore           1
2.97 Crore           1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.67 Crore           1
4.86 Crore           1
2.62 Crore           1
90.5 Lac             1
52.5 Lac             1
53.2 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
6.25 Crore           1
2.77 Crore           1
47.5 Lac             1
4.16 Crore           1
4.52 Crore           1
1.74 Crore           1
9.3 Crore            1
4.21 Crore           1
97.5 Lac             1
2.64 Crore           1
2.49 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
8.44 Crore           1
1.84 Crore           1
13.2 Crore           1
2.92 Crore           1
2.38 Crore           1
5.15 Crore           1
16 Lac               1
49.5 Lac             1
9.2 Crore            1
9.95 Crore           1
86.99 Lac            1
87.99 Lac            1
37.1 Lac             1
2.86 Crore           1
7.4 Crore            1
86.92 Lac            1
64.45 Lac            1
2.34 Crore           1
3.79 Crore           1
3.39 Crore           1
94.99 Lac            1
88.4 Lac             1
3.72 Crore           1
57 Lac               1
95.5 Lac             1
96.07 Lac            1
19 Lac               1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64
(440,)

In [16]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN,Z68804716
1645,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5...",S65406842
1973,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of...",Q70122610
2055,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5...",M69984000
2358,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",L69416788
2523,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of...",A69074608
2550,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN,X66482366
2641,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ...",A69074608
2951,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of...",F62164440
2964,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN,H28672425
2965,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5...",E22752179

In [17]:
df = df[df['price'] != 'Price on Request']  ## keeping only the rows which have exact prices 
df[df['price'] == 'Price on Request']

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating, property_id]
Index: []

In [18]:
## standardizing the prices in Cr
def clean_price(x):
    if type(x) == float:
        return x
    if len(x)<2:
        return None
    
    if x[1] == 'Lac':
        return float(x[0])/100
    else:
        return float(x[0])

In [19]:
df['price']= df['price'].str.split(' ').apply(clean_price)

In [20]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [21]:
print(df['price'].value_counts())
print(df['price'].value_counts().shape)

price
1.2500     79
1.1000     61
1.4000     60
1.2000     59
1.5000     59
0.9000     58
1.3000     57
0.9500     53
2.0000     51
1.7500     47
1.0000     46
1.6000     43
1.3500     41
1.9000     40
1.5500     40
0.7500     38
1.6500     38
1.8000     37
1.7000     37
0.8000     36
2.2000     34
1.1500     33
0.5000     33
1.4500     31
0.8500     31
1.0500     30
2.5000     29
0.6000     29
0.4000     29
2.1000     26
0.4500     26
0.6500     25
0.3500     23
1.8500     23
2.3500     23
3.0000     22
0.7000     21
2.2500     20
0.5500     20
3.5000     19
2.3000     18
2.4000     18
0.3000     17
2.6500     16
1.3800     15
2.6000     15
2.4500     14
3.4000     14
2.1500     14
0.8200     13
0.7800     13
0.3800     13
0.9200     13
2.7000     13
1.3200     13
3.2500     13
0.4200     12
1.9500     12
5.0000     12
2.8000     12
1.4200     12
0.8800     11
0.2500     11
0.3200     11
1.0800     11
1.2800     10
0.2600     10
0.8700     10
1.1200     10
1.7800     10
2.5500     10
0.2800     10
2.8500      9
1.6800      9
1.7200      9
3.4500      9
0.9900      9
2.0500      9
4.0000      9
0.3600      9
0.2200      9
0.4800      8
0.2000      8
0.2700      8
0.8600      8
4.2500      8
2.7500      8
1.2600      8
6.5000      8
1.5400      8
1.1800      8
1.7600      8
3.2000      8
6.0000      8
0.9800      8
0.5600      8
0.7200      7
0.3900      7
1.2900      7
2.9000      7
1.2700      7
1.3600      7
0.4600      7
3.7000      7
1.9900      7
1.1900      7
1.0200      7
0.9700      7
3.3000      7
0.7900      7
1.1600      6
2.9500      6
1.1400      6
0.9600      6
3.0500      6
1.5100      6
1.4900      6
0.7150      6
4.1000      6
1.0700      6
5.5000      6
1.5900      6
3.6500      6
0.2100      6
0.5400      6
1.3400      6
1.0100      6
0.3700      6
3.3500      6
0.4300      6
3.9000      6
1.1300      6
1.3900      6
1.9800      6
1.2400      5
6.7500      5
1.3300      5
0.2900      5
1.4700      5
2.2200      5
3.7500      5
0.9300      5
1.4400      5
1.6900      5
1.9100      5
0.4900      5
1.8200      5
1.8300      5
1.7900      5
1.6200      5
2.2900      5
1.9200      5
1.9300      5
4.5000      5
0.6800      5
0.2400      5
0.6600      5
1.4300      5
2.1200      5
0.6400      5
2.7800      5
1.1700      5
0.5800      4
0.2850      4
1.7100      4
1.2200      4
4.3000      4
1.4800      4
6.1500      4
3.1000      4
7.0000      4
4.8500      4
0.8900      4
0.7300      4
0.3100      4
1.6600      4
0.6700      4
1.2300      4
0.3650      4
0.3300      4
1.5800      4
1.3100      4
5.9000      4
2.0900      4
0.4150      4
5.6000      4
0.7400      4
1.3700      4
1.5200      4
5.2500      4
1.7300      4
0.6200      4
3.6000      4
1.7700      4
1.6400      4
3.9500      4
4.7500      3
3.8000      3
1.0400      3
2.2800      3
2.0300      3
1.0900      3
2.0800      3
1.6700      3
1.5700      3
2.3600      3
0.9100      3
4.8000      3
2.5100      3
3.1500      3
2.2400      3
0.5200      3
0.6900      3
0.8300      3
1.2100      3
2.0100      3
0.9400      3
1.4100      3
0.7250      3
0.5100      3
1.6300      3
5.8000      3
0.8400      3
0.3400      3
2.3300      3
3.8500      3
2.7900      3
1.8800      3
0.6450      3
3.4900      3
4.2000      3
0.4700      3
0.5620      2
3.5500      2
7.5000      2
0.2710      2
11.0000     2
4.5500      2
2.8700      2
2.1400      2
0.5256      2
0.8750      2
2.9900      2
1.5600      2
2.2600      2
2.5800      2
2.5700      2
2.0400      2
3.2900      2
2.5200      2
8.5000      2
8.0000      2
2.1700      2
0.7100      2
4.4900      2
0.5900      2
0.7750      2
0.5300      2
5.7000      2
2.2300      2
6.2000      2
0.5350      2
5.2000      2
0.2775      2
4.7000      2
0.8850      2
14.0000     2
2.0200      2
2.4100      2
3.3200      2
4.6000      2
3.2100      2
0.2550      2
4.2600      2
4.4500      2
0.9850      2
1.4600      2
2.1300      2
0.3150      2
2.9100      2
1.8700      2
0.4100      2
3.1900      1
5.3100      1
4.9500      1
4.0200      1
0.9704      1
0.3750      1
0.6885      1
3.2300      1
2.6900      1
2.5400      1
0.5480      1
3.9800      1
2.4400      1
9.0000      1
0.8250      1
0.6100      1
0.9450      1
0.2980      1
6.0200      1
7.9000      1
15.0000     1
7.8000      1
1.9700      1
0.3950      1
11.2500     1
7.1500      1
2.8200      1
0.5499      1
8.2500      1
4.6700      1
0.3175      1
3.8700      1
2.3700      1
2.6300      1
1.1100      1
6.4400      1
0.9810      1
0.5550      1
0.9575      1
3.4600      1
3.6300      1
3.3900      1
5.4000      1
0.5560      1
0.6699      1
0.2300      1
5.4900      1
6.3000      1
2.9800      1
4.6300      1
2.3400      1
6.1600      1
5.3000      1
2.7200      1
4.7800      1
2.2100      1
2.4800      1
0.8950      1
0.9950      1
3.8300      1
4.4000      1
3.7900      1
0.3550      1
0.7120      1
0.2750      1
0.2350      1
4.7900      1
0.7990      1
3.6700      1
1.0600      1
0.2610      1
4.9400      1
9.1400      1
8.3500      1
0.8100      1
10.7500     1
0.1750      1
0.2450      1
10.0000     1
5.7500      1
2.1100      1
6.1000      1
2.7700      1
7.5600      1
6.2500      1
0.6850      1
0.9375      1
0.8550      1
2.9700      1
0.9425      1
0.2999      1
0.8050      1
2.6200      1
0.5320      1
0.9050      1
0.5250      1
0.6550      1
0.4750      1
0.4250      1
2.6100      1
0.2050      1
1.7400      1
4.2100      1
4.5200      1
8.4400      1
1.8400      1
4.1600      1
5.1500      1
2.9200      1
13.2000     1
2.6400      1
2.3800      1
2.4900      1
0.6340      1
2.0600      1
0.9750      1
2.0700      1
0.4400      1
2.3200      1
1.8600      1
0.8575      1
0.8799      1
9.3000      1
4.8600      1
9.9500      1
0.8699      1
9.2000      1
0.4950      1
0.8692      1
3.9900      1
0.1600      1
2.8600      1
7.4000      1
3.7800      1
0.9888      1
0.2950      1
0.9499      1
0.8840      1
0.6445      1
0.3710      1
0.5700      1
3.7200      1
0.1900      1
0.9550      1
0.7085      1
7.5200      1
0.4030      1
0.9607      1
0.3250      1
2.9600      1
1.5300      1
0.2690      1
0.2650      1
0.7353      1
0.8977      1
0.6250      1
Name: count, dtype: int64
(438,)

In [22]:
df['price_per_sqft'].value_counts().shape

(2129,)

In [23]:
df = df[~(df.astype(str) == df.columns).any(axis=1)]

In [24]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 3008
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   society          2997 non-null   object
 2   price            2996 non-null   float64
 3   price_per_sqft   2996 non-null   float64
 4   areaWithType     2997 non-null   object
 5   bedRoom          2997 non-null   object
 6   bathroom         2997 non-null   object
 7   balcony          2997 non-null   object
 8   additionalRoom   1692 non-null   object
 9   address          2991 non-null   object
 10  floorNum         2995 non-null   object
 11  facing           2123 non-null   object
 12  agePossession    2996 non-null   object
 13  nearbyLocations  2906 non-null   object
 14  description      2997 non-null   object
 15  furnishDetails   2200 non-null   object
 16  features         2590 non-null   object
 17  rating           2668 non-null   object
 18  property_id      2997 non-null   object
dtypes: float64(2), object(17)
memory usage: 468.3+ KB

In [26]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [27]:
df['areaWithType'].value_counts()  ## This column has multiple values so it'll require some sort of feature engg.

areaWithType
Super Built up area 1350(125.42 sq.m.)                                                                                          17
Super Built up area 1578(146.6 sq.m.)                                                                                           17
Super Built up area 1950(181.16 sq.m.)Carpet area: 1161 sq.ft. (107.86 sq.m.)                                                   17
Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)                                                    15
Super Built up area 2010(186.74 sq.m.)                                                                                          14
Super Built up area 2150(199.74 sq.m.)                                                                                          12
Carpet area: 1650 (153.29 sq.m.)                                                                                                11
Super Built up area 1950(181.16 sq.m.)                                                                                          11
Super Built up area 1650(153.29 sq.m.)                                                                                          10
Super Built up area 1550(144 sq.m.)                                                                                             10
Carpet area: 1150 (106.84 sq.m.)                                                                                                10
Super Built up area 1920(178.37 sq.m.)                                                                                          10
Carpet area: 1450 (134.71 sq.m.)                                                                                                 9
Super Built up area 1828(169.83 sq.m.)                                                                                           9
Super Built up area 1640(152.36 sq.m.)                                                                                           9
Carpet area: 489 (45.43 sq.m.)                                                                                                   9
Carpet area: 1350 (125.42 sq.m.)                                                                                                 9
Carpet area: 1950 (181.16 sq.m.)                                                                                                 8
Carpet area: 900 (83.61 sq.m.)                                                                                                   8
Carpet area: 2400 (222.97 sq.m.)                                                                                                 8
Carpet area: 1800 (167.23 sq.m.)                                                                                                 8
Super Built up area 1760(163.51 sq.m.)Built Up area: 1186 sq.ft. (110.18 sq.m.)Carpet area: 1130 sq.ft. (104.98 sq.m.)           8
Super Built up area 1366(126.91 sq.m.)                                                                                           8
Carpet area: 750 (69.68 sq.m.)                                                                                                   8
Super Built up area 1200(111.48 sq.m.)                                                                                           7
Super Built up area 1930(179.3 sq.m.)                                                                                            7
Super Built up area 2364(219.62 sq.m.)                                                                                           7
Super Built up area 3400(315.87 sq.m.)                                                                                           7
Carpet area: 1600 (148.64 sq.m.)                                                                                                 7
Super Built up area 1538(142.88 sq.m.)                                                                                           7
Super Built up area 2200(204.39 sq.m.)                                                                                           7
Super Built up area 2350(218.32 sq.m.)                                                                                           7
Super Built up area 1415(131.46 sq.m.)                                                                                           7
Carpet area: 1103 (102.47 sq.m.)                                                                                                 7
Carpet area: 1300 (120.77 sq.m.)                                                                                                 7
Carpet area: 1760 (163.51 sq.m.)                                                                                                 7
Carpet area: 2300 (213.68 sq.m.)                                                                                                 7
Super Built up area 2408(223.71 sq.m.)                                                                                           7
Super Built up area 2100(195.1 sq.m.)                                                                                            7
Super Built up area 2727(253.35 sq.m.)                                                                                           6
Super Built up area 1750(162.58 sq.m.)                                                                                           6
Carpet area: 1423 (132.2 sq.m.)                                                                                                  6
Carpet area: 1326 (123.19 sq.m.)                                                                                                 6
Super Built up area 1572(146.04 sq.m.)                                                                                           6
Super Built up area 1568(145.67 sq.m.)                                                                                           6
Super Built up area 2290(212.75 sq.m.)                                                                                           6
Carpet area: 822 (76.37 sq.m.)                                                                                                   6
Super Built up area 3150(292.64 sq.m.)                                                                                           6
Super Built up area 2812(261.24 sq.m.)                                                                                           6
Carpet area: 700 (65.03 sq.m.)                                                                                                   6
Super Built up area 2215(205.78 sq.m.)                                                                                           6
Carpet area: 1200 (111.48 sq.m.)                                                                                                 5
Carpet area: 1975 (183.48 sq.m.)                                                                                                 5
Carpet area: 2000 (185.81 sq.m.)                                                                                                 5
Super Built up area 1435(133.32 sq.m.)                                                                                           5
Super Built up area 1700(157.94 sq.m.)                                                                                           5
Super Built up area 1245(115.66 sq.m.)                                                                                           5
Super Built up area 1970(183.02 sq.m.)                                                                                           5
Super Built up area 2000(185.81 sq.m.)                                                                                           5
Super Built up area 1000(92.9 sq.m.)                                                                                             5
Built Up area: 700 (65.03 sq.m.)                                                                                                 5
Super Built up area 1975(183.48 sq.m.)                                                                                           5
Super Built up area 1360(126.35 sq.m.)                                                                                           5
Carpet area: 1050 (97.55 sq.m.)                                                                                                  5
Super Built up area 1215(112.88 sq.m.)                                                                                           5
Super Built up area 1457(135.36 sq.m.)Carpet area: 849 sq.ft. (78.87 sq.m.)                                                      5
Super Built up area 2149(199.65 sq.m.)                                                                                           5
Super Built up area 2025(188.13 sq.m.)                                                                                           5
Super Built up area 1960(182.09 sq.m.)                                                                                           5
Super Built up area 1480(137.5 sq.m.)                                                                                            5
Super Built up area 1850(171.87 sq.m.)                                                                                           5
Carpet area: 450 (41.81 sq.m.)                                                                                                   5
Carpet area: 600 (55.74 sq.m.)                                                                                                   5
Super Built up area 1997(185.53 sq.m.)                                                                                           5
Carpet area: 850 (78.97 sq.m.)                                                                                                   5
Carpet area: 645 (59.92 sq.m.)                                                                                                   5
Super Built up area 1565(145.39 sq.m.)                                                                                           5
Super Built up area 2812(261.24 sq.m.)Built Up area: 2600 sq.ft. (241.55 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)           5
Super Built up area 1875(174.19 sq.m.)                                                                                           5
Super Built up area 1100(102.19 sq.m.)                                                                                           4
Super Built up area 1081(100.43 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)                                                                                           4
Super Built up area 650(60.39 sq.m.)                                                                                             4
Super Built up area 2355(218.79 sq.m.)Built Up area: 1535 sq.ft. (142.61 sq.m.)Carpet area: 1403 sq.ft. (130.34 sq.m.)           4
Super Built up area 1103(102.47 sq.m.)                                                                                           4
Super Built up area 1790(166.3 sq.m.)                                                                                            4
Built Up area: 2040 (189.52 sq.m.)                                                                                               4
Super Built up area 1430(132.85 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)                                                  4
Super Built up area 1780(165.37 sq.m.)                                                                                           4
Super Built up area 1261(117.15 sq.m.)                                                                                           4
Super Built up area 1385(128.67 sq.m.)Built Up area: 940 sq.ft. (87.33 sq.m.)Carpet area: 845 sq.ft. (78.5 sq.m.)                4
Super Built up area 1725(160.26 sq.m.)                                                                                           4
Super Built up area 1727(160.44 sq.m.)Carpet area: 1017 sq.ft. (94.48 sq.m.)                                                     4
Super Built up area 1365(126.81 sq.m.)                                                                                           4
Super Built up area 2400(222.97 sq.m.)                                                                                           4
Super Built up area 2545(236.44 sq.m.)                                                                                           4
Carpet area: 1250 (116.13 sq.m.)                                                                                                 4
Carpet area: 1500 (139.35 sq.m.)                                                                                                 4
Super Built up area 2191(203.55 sq.m.)                                                                                           4
Built Up area: 1103 (102.47 sq.m.)                                                                                               4
Super Built up area 600(55.74 sq.m.)                                                                                             4
Carpet area: 1225 (113.81 sq.m.)                                                                                                 4
Super Built up area 1825(169.55 sq.m.)                                                                                           4
Super Built up area 2358(219.07 sq.m.)                                                                                           4
Super Built up area 1789(166.2 sq.m.)                                                                                            4
Carpet area: 1549 (143.91 sq.m.)                                                                                                 4
Super Built up area 2950(274.06 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)Built Up area: 1600 sq.ft. (148.64 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)         4
Super Built up area 1310(121.7 sq.m.)                                                                                            4
Super Built up area 1300(120.77 sq.m.)                                                                                           4
Super Built up area 1942(180.42 sq.m.)                                                                                           4
Carpet area: 2290 (212.75 sq.m.)                                                                                                 4
Super Built up area 2802(260.31 sq.m.)Built Up area: 2225.56 sq.ft. (206.76 sq.m.)                                               4
Carpet area: 501 (46.54 sq.m.)                                                                                                   4
Super Built up area 2095(194.63 sq.m.)                                                                                           4
Carpet area: 1400 (130.06 sq.m.)                                                                                                 4
Carpet area: 800 (74.32 sq.m.)                                                                                                   4
Built Up area: 1350 (125.42 sq.m.)                                                                                               4
Super Built up area 1457(135.36 sq.m.)                                                                                           4
Super Built up area 1930(179.3 sq.m.)Built Up area: 1929 sq.ft. (179.21 sq.m.)Carpet area: 1928 sq.ft. (179.12 sq.m.)            4
Carpet area: 1340 (124.49 sq.m.)                                                                                                 4
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)           4
Carpet area: 481.73 (44.75 sq.m.)                                                                                                4
Carpet area: 1180 (109.63 sq.m.)                                                                                                 3
Super Built up area 576(53.51 sq.m.)                                                                                             3
Carpet area: 554.16 (51.48 sq.m.)                                                                                                3
Super Built up area 2125(197.42 sq.m.)                                                                                           3
Carpet area: 685 (63.64 sq.m.)                                                                                                   3
Super Built up area 1743(161.93 sq.m.)                                                                                           3
Super Built up area 1298(120.59 sq.m.)                                                                                           3
Carpet area: 690 (64.1 sq.m.)                                                                                                    3
Super Built up area 2361(219.34 sq.m.)                                                                                           3
Built Up area: 2000 (185.81 sq.m.)                                                                                               3
Super Built up area 1283(119.19 sq.m.)Built Up area: 978.23 sq.ft. (90.88 sq.m.)Carpet area: 734.43 sq.ft. (68.23 sq.m.)         3
Carpet area: 531 (49.33 sq.m.)                                                                                                   3
Carpet area: 2298 (213.49 sq.m.)                                                                                                 3
Super Built up area 1929(179.21 sq.m.)                                                                                           3
Carpet area: 1075 (99.87 sq.m.)                                                                                                  3
Built Up area: 2400 (222.97 sq.m.)                                                                                               3
Carpet area: 710 (65.96 sq.m.)                                                                                                   3
Super Built up area 1735(161.19 sq.m.)                                                                                           3
Super Built up area 1671(155.24 sq.m.)                                                                                           3
Carpet area: 990 (91.97 sq.m.)                                                                                                   3
Carpet area: 1210 (112.41 sq.m.)                                                                                                 3
Carpet area: 2500 (232.26 sq.m.)                                                                                                 3
Carpet area: 3100 (288 sq.m.)                                                                                                    3
Super Built up area 735(68.28 sq.m.)                                                                                             3
Carpet area: 1385 (128.67 sq.m.)                                                                                                 3
Super Built up area 1620(150.5 sq.m.)                                                                                            3
Carpet area: 2100 (195.1 sq.m.)                                                                                                  3
Super Built up area 1295(120.31 sq.m.)                                                                                           3

In [28]:
## preprocessing bedRoom

df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [29]:
df['bedRoom'].isnull().sum()

np.int64(0)

In [30]:
df['bedRoom'] = df['bedRoom'].astype(str).str.split(' ').str.get(0).astype('int')

In [31]:
## preprocessing batroom col
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [32]:
df['bathroom'].isnull().sum()

np.int64(0)

In [33]:
df['bathroom'] = df['bathroom'].astype(str).str.split(' ').str.get(0).astype('int')

In [34]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [35]:
## preprocessing balcony 

df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [36]:
df['balcony'].isnull().sum()

np.int64(0)

In [37]:
df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

0        1
1        1
2        3
3        2
4        3
5        3
6        3
7        3
8       3+
9        2
10       2
11       1
12       3
13      3+
14       3
15       3
16       0
17       2
18       3
19       3
20       2
21      3+
22       3
23      3+
24      3+
26       1
27       2
28      3+
29       2
30       0
31       2
32      3+
33       1
34       2
35       3
36      3+
37       2
38       2
39       3
40       2
41      3+
42      3+
43      3+
44       2
45      3+
46      3+
47       2
48      3+
49      3+
50      3+
51       2
52       3
53       2
54       2
55      3+
56       1
57       1
58       1
59       2
60       2
61       3
62      3+
63       2
64      3+
65       3
66      3+
67       3
68       2
69       2
70       3
71       3
72       2
73       1
74       3
75       2
76       2
77       3
78      3+
79       3
80       2
81       0
82       1
83      3+
84       1
85       1
86      3+
87       1
88       1
89       1
90       2
91       2
92       2
93       0
94       0
95       2
96      3+
97       2
98       2
99       2
100      3
101      3
102      3
103      2
104      2
105     3+
106     3+
107      3
108      1
109      2
110      2
111      1
112      2
113      2
114      2
115      1
116     3+
117      2
118     3+
119     3+
120      2
121      1
122      1
123      3
124      3
125      2
126      3
127      2
128      2
129      0
130      3
131      0
132      1
133      1
134      1
135      2
136      2
137      1
138      1
139      3
140     3+
141      3
142      0
143      3
144      2
145      3
146      3
147     3+
148      3
149      1
150      3
151      1
152      3
153      2
154      1
155      3
156      1
157      3
158      3
159      1
160      3
161     3+
162      2
163      2
164      2
165     3+
166      0
167      1
168      3
169      2
170      3
171      2
172      2
173     3+
174     3+
175     3+
176     3+
177      3
178      2
179      3
180     3+
181      0
182      3
183      1
184      3
185     3+
186      3
187      3
188      1
189      1
190      1
191     3+
192      0
193     3+
194      3
195      0
196      3
197     3+
198      1
199      2
200      3
201      1
202      0
203      3
204     3+
205      3
206      0
207      1
208      3
209      1
210      3
211      3
212      3
213      1
214      2
215      2
216     3+
217      3
218      2
219     3+
220      3
221      3
222      3
223      3
224      1
225      1
226      2
227      3
228      3
229     3+
230      3
231      2
232      1
233      2
234      3
235      2
236      3
237     3+
238      3
239      3
240      2
241      3
242      1
243      2
244     3+
245      3
246      2
247      3
248      3
249      2
250      3
251      1
252      3
253      2
254      3
255      3
256      3
257      3
258      2
259     3+
260      2
261      3
262      3
263      3
264      3
265     3+
266     3+
267      2
268      2
269     3+
270      3
271      2
272     3+
273      2
274     3+
275      0
276      2
277      3
278      0
279      0
280      0
281     3+
282      3
283      2
284      3
285      3
287      3
288      3
289     3+
290     3+
291      2
292     3+
293     3+
294      2
295      3
296      3
297      3
298      2
299      2
300      3
301      3
302      1
303      3
304      1
305      2
306      2
307      3
308     3+
309     3+
310      2
311      3
312      2
313      2
314     3+
315     3+
316      3
317     3+
318      3
319     3+
320      3
321     3+
322     3+
323      2
324      3
325      3
326      2
327      3
328      3
329      1
330      3
331      1
332      2
333      2
334      3
335     3+
336      3
337      2
338     3+
339      3
340      3
341     3+
342      3
343     3+
344     3+
345      3
346     3+
347     3+
348      2
349      1
350      1
351      3
352      2
353      1
354      3
355      3
356     3+
357      2
358      3
359      3
360     3+
361      3
362     3+
363      3
364      2
365      2
366      3
367     3+
368      2
369      2
370      3
371      3
372      2
373      2
374     3+
375      3
376     3+
377     3+
378      1
379      3
380      3
381      2
382     3+
383     3+
384     3+
385     3+
386     3+
387      3
388      3
389     3+
390      3
391     3+
392      2
393      3
394      3
395     3+
396      3
397      2
398      2
399      2
400      3
401      3
402      3
403      2
404     3+
405      2
406      3
407     3+
408      3
409     3+
410      2
411     3+
412     3+
413     3+
414     3+
415      3
416     3+
417      3
418      3
419      1
420      2
421     3+
422     3+
423     3+
424      2
425     3+
426     3+
427     3+
428      2
429      3
430     3+
431      3
432     3+
433      3
434      3
435      3
436      3
437      2
438      3
439      2
440     3+
441      3
442      3
443      3
444     3+
445      2
446     3+
447      3
448      2
449     3+
450      3
451      3
452      3
453     3+
454     3+
455     3+
456     3+
457      3
458     3+
459      3
460      3
461     3+
462      2
463      2
464     3+
465     3+
466     3+
467     3+
468     3+
469     3+
470      2
471      3
472      3
473     3+
474     3+
475      3
476      3
477     3+
478      3
479     3+
480      3
481     3+
482      3
483      3
484      3
485      3
486     3+
487     3+
488     3+
489     3+
490      3
491      3
492      3
493     3+
494     3+
495      3
496      1
497     3+
498     3+
499     3+
500      3
501      2
502     3+
503      3
504      2
505      2
506      3
507      3
508     3+
509     3+
510     3+
511      3
512     3+
513      3
514      3
515     3+
516     3+
517     3+
518     3+
519      2
520     3+
521     3+
522     3+
523      3
524      3
525      2
526     3+
527      3
528      2
529      3
530     3+
531     3+
532     3+
533      3
534      2
535     3+
536      3
537      3
538     3+
539     3+
540      3
541     3+
542      3
543     3+
544     3+
545      2
546      2
547     3+
548     3+
549     3+
550      3
551      2
552      3
553     3+
554     3+
555      2
556      3
557     3+
558      2
559      3
560     3+
561      3
562      1
563      2
564      3
565     3+
566     3+
567     3+
568     3+
569     3+
570     3+
571     3+
572     3+
573      3
574     3+
575      3
576      3
577      2
578      2
579      3
580     3+
581     3+
582     3+
583      3
584     3+
585     3+
586     3+
587     3+
588      3
589      3
590      2
591     3+
592      2
593      2
594     3+
595     3+
596     3+
597     3+
598     3+
599     3+
600     3+
601     3+
602     3+
603      3
604     3+
605      3
606      3
607     3+
608     3+
609     3+
610      3
611      3
612     3+
613     3+
614      1
615     3+
616     3+
617     3+
618      3
619     3+
620      3
621      3
622     3+
623      3
624     3+
625     3+
626     3+
627      3
628      3
629      2
630      3
631      3
632     3+
633      2
634     3+
635     3+
636      3
637     3+
638      3
639      2
640     3+
641      2
642     3+
643     3+
644     3+
645      3
646     3+
647     3+
648     3+
649     3+
650     3+
651     3+
652     3+
653      3
654     3+
655      3
656     3+
657      3
658      2
659      3
660     3+
661      3
662      3
663      3
664     3+
665      3
666      3
667      1
668     3+
669     3+
670     3+
671      3
672      3
673      3
674     3+
675     3+
676      3
677     3+
678      3
679     3+
680      3
681     3+
682      3
683      3
684     3+
685     3+
686     3+
687      2
688      3
689      3
690     3+
691      2
692      3
693      3
694      3
695      2
696      2
697     3+
698     3+
699     3+
700      3
701     3+
702     3+
703      3
704      2
705      3
706      3
707      3
708      3
709     3+
710      3
711     3+
712     3+
713     3+
714     3+
715     3+
716      2
717      3
718      3
719     3+
720     3+
721      2
722      2
723      2
724      2
725      3
726     3+
727      3
728      1
729      3
730      2
731      2
732     3+
733      3
734     3+
735     3+
736     3+
737     3+
738      3
739      3
740     3+
741      2
742      2
743      3
744     3+
745      3
746      2
747     3+
748     3+
749     3+
750      3
751      2
752      3
753      3
754      3
755     3+
756     3+
757     3+
758      3
759     3+
760      3
761     3+
762     3+
763      2
764      2
765      2
766      3
767     3+
768      3
769     3+
770     3+
771      2
772     3+
773     3+
774      2
775      2
776      3
777      3
778     3+
779      3
780      3
781      3
782      3
783      1
784     3+
785      3
786     3+
787     3+
788     3+
789      2
790      3
791      1
792     3+
793     3+
794      3
795      3
796      3
797      3
798      3
799     3+
800      3
801      3
802     3+
803     3+
804      3
805      3
806      3
807      3
808      3
809      2
810      3
811     3+
812      3
813      2
814     3+
815      2
816      3
817      2
818      2
819     3+
820     3+
821      3
822     3+
823      3
824      1
825      2
826      1
827      1
828      2
829      2
830     3+
831     3+
832      3
833     3+
834     3+
835      3
836     3+
837      2
838     3+
839     3+
840      3
841      3
842     3+
843      3
844      3
845     3+
846      3
847      3
848      3
849      3
850      3
851      3
852      3
853     3+
854      3
855     3+
856     3+
857      3
858      3
859      3
860      3
861     3+
862     3+
863      3
864      2
865      3
866      2
867      3
868     3+
869      3
870      2
871      2
872      3
873     3+
874      3
875      2
876      2
877      3
878      2
879     3+
880     3+
881      3
882     3+
883      3
884      1
885      3
886      3
887     3+
888     3+
889     3+
890     3+
891      3
892      2
893     3+
894     3+
895     3+
896      3
897     3+
898     3+
899      3
900      3
901      3
902      3
903      3
904      3
905      2
906      2
907      3
908      3
909      3
910      3
911     3+
912      3
913     3+
914      3
915      2
916      2
917      3
918      1
919      2
920     3+
921      2
922      3
923     3+
924     3+
925      3
926     3+
927      3
928      3
929      2
930      3
931     3+
932      2
933      3
934     3+
935     3+
936      2
937     3+
938     3+
939     3+
940      2
941      2
942     3+
943      3
944      3
945      1
946      1
947     3+
948     3+
949      3
950      2
951      3
952     3+
953     3+
954      2
955      3
956     3+
957     3+
958      3
959      2
960      2
961     3+
962     3+
963      3
964     3+
965     3+
966     3+
967     3+
968      2
969     3+
970     3+
971     3+
972     3+
973     3+
974     3+
975     3+
976      3
977      3
978      3
979      1
980      2
981      2
982      3
983      3
984      3
985     3+
986      2
987      3
988      3
989      3
990      3
991      3
992      2
993      2
994      3
995      3
996     3+
997      3
998      2
999     3+
1000    3+
1001     3
1002    3+
1003    3+
1004    3+
1005     2
1006     3
1007     2
1008     3
1009     3
1010     3
1011     3
1012     3
1013     3
1014     2
1015     2
1016    3+
1017     3
1018    3+
1019    3+
1020    3+
1021     2
1022    3+
1023    3+
1024    3+
1025    3+
1026    3+
1027    3+
1028     2
1029     3
1030     3
1031    3+
1032     2
1033     2
1034    3+
1035     3
1036    3+
1037     3
1038    3+
1039     3
1040    3+
1041    3+
1042    3+
1043     3
1044    3+
1045    3+
1046    3+
1047     3
1048     3
1049     3
1050     2
1051     1
1052     3
1053    3+
1054     3
1055    3+
1056     2
1057     2
1058     3
1059     2
1060     2
1061    3+
1062     3
1063     2
1064     3
1065     2
1066    3+
1067    3+
1068     3
1069     3
1070     3
1071     3
1072     3
1073    3+
1074     2
1075    3+
1076    3+
1077    3+
1078     3
1079    3+
1080     3
1081     3
1082     2
1083    3+
1084     2
1085     2
1086     2
1087     2
1088     1
1089     1
1090     3
1091     3
1092     3
1093    3+
1094    3+
1095    3+
1096    3+
1097     3
1098     1
1099    3+
1100    3+
1101     3
1102    3+
1103     2
1104    3+
1105     2
1106     2
1107    3+
1108    3+
1109    3+
1110     2
1111     2
1112     2
1113    3+
1114     3
1115     3
1116     2
1117     2
1118     2
1119     3
1120     2
1121     1
1122     2
1123    3+
1124    3+
1125     2
1126     2
1127    3+
1128    3+
1129     3
1130    3+
1131    3+
1132     3
1133    3+
1134     1
1135     1
1136     1
1137     1
1138     1
1139     1
1140     1
1141     1
1142     1
1143     3
1144     1
1145     2
1146     2
1147     1
1148     2
1149     1
1150    3+
1151     1
1152     3
1153     1
1154     2
1155     3
1156     2
1157     2
1158     2
1159     2
1160     1
1161     2
1162     2
1163     2
1164     2
1165     2
1166     3
1167     3
1168     3
1169     2
1170     2
1171     3
1172     2
1173     1
1174    3+
1175     3
1176    3+
1177     3
1178     3
1179    3+
1180     2
1181     3
1182    3+
1183     3
1184     3
1185     3
1186     3
1187     3
1188     3
1189     2
1190     3
1191     2
1192     3
1193     3
1194     3
1195    3+
1196    3+
1197     2
1198     2
1199     3
1200     3
1201     3
1202    3+
1203     3
1204     3
1205    3+
1206    3+
1207     3
1208     2
1209     1
1210     1
1211     2
1212    3+
1213     3
1214    3+
1215     3
1216     2
1217     3
1218     3
1219     2
1220     2
1221    3+
1222     1
1223     1
1224     2
1225    3+
1226    3+
1227    3+
1228    3+
1229    3+
1230    3+
1231     3
1232    3+
1233     2
1234     3
1235    3+
1236    3+
1237    3+
1238    3+
1239     3
1240    3+
1241     3
1242    3+
1243     3
1244    3+
1245     3
1246     3
1247     3
1248     3
1249     3
1250     3
1251     3
1252     3
1253     3
1254     3
1255     3
1256     3
1257     3
1258     2
1259     3
1260     1
1261     1
1262     1
1263     1
1264     3
1265     2
1266     3
1267     3
1268     3
1269     3
1270     3
1271     3
1272    3+
1273    3+
1274     2
1275     3
1276    3+
1277    3+
1278     3
1279     3
1280    3+
1281    3+
1282    3+
1283     2
1284     2
1285     2
1286    3+
1287    3+
1288    3+
1289    3+
1290     3
1291     3
1292     2
1293     3
1294     3
1295     3
1296     2
1297     3
1298     2
1299     1
1300     3
1301    3+
1302    3+
1303     3
1304     2
1305     3
1306     2
1307     1
1308     1
1309     1
1310     1
1311     1
1312     1
1313     1
1314     3
1315     3
1316    3+
1317    3+
1318    3+
1319     2
1320    3+
1321    3+
1322    3+
1323     3
1324    3+
1325     2
1326    3+
1327     3
1328     1
1329     3
1330     1
1331     1
1332     1
1333     1
1334     1
1335     1
1336    3+
1337     3
1338     1
1339     2
1340     3
1341     2
1342     3
1343     1
1344    3+
1345     3
1346    3+
1347     3
1348    3+
1349    3+
1350    3+
1351     2
1352    3+
1353    3+
1354    3+
1355    3+
1356     3
1357    3+
1358     3
1359     3
1360     1
1361     3
1362    3+
1363    3+
1364    3+
1365    3+
1366     2
1367    3+
1368     3
1369    3+
1370     3
1371     3
1372    3+
1373     3
1374    3+
1375     2
1376    3+
1377    3+
1378    3+
1379     1
1380     3
1381     3
1382     3
1383     3
1384     3
1385     3
1386     3
1387     3
1388     3
1389     2
1390     3
1391     3
1392     2
1393     3
1394     3
1395     1
1396     3
1397     3
1398    3+
1399     3
1400     3
1401     3
1402     3
1403     3
1404     2
1405     2
1406     2
1407     1
1408     3
1409    3+
1410     2
1411     3
1412     3
1413    3+
1414     3
1415     3
1416    3+
1417     3
1418    3+
1419     1
1420    3+
1421    3+
1422     1
1423     1
1424     3
1425     3
1426     3
1427    3+
1428     3
1429     3
1430     3
1431    3+
1432     3
1433     2
1434     3
1435    3+
1436     3
1437     3
1438     3
1439     3
1440     2
1441     2
1442     3
1443     2
1444     3
1445     3
1446    3+
1447     3
1448    3+
1449     3
1450     3
1451     2
1452     3
1453     3
1454     2
1455    3+
1456    3+
1457    3+
1458     3
1459    3+
1460    3+
1461    3+
1462     2
1463     2
1464     3
1465     3
1466     3
1467    3+
1468     3
1469     3
1470     2
1471     3
1472    3+
1473     3
1474     3
1475     3
1476    3+
1477    3+
1478    3+
1479    3+
1480     3
1481     3
1482     3
1483     3
1484     3
1485    3+
1486     3
1487    3+
1488    3+
1489    3+
1490     3
1491    3+
1492     3
1493     3
1494     3
1495     3
1496    3+
1497    3+
1498     3
1499    3+
1500    3+
1501    3+
1502    3+
1503    3+
1504    3+
1505     2
1506     3
1507     2
1508    3+
1509    3+
1510     2
1511     3
1512    3+
1513     3
1514    3+
1515    3+
1516     3
1517     2
1518    3+
1519    3+
1520     3
1521     3
1522     3
1523     3
1524     3
1525     3
1526     3
1527     3
1528     3
1529     3
1530     3
1531     3
1532     3
1533     3
1534     3
1535     3
1536     3
1537     3
1538     3
1539    3+
1540    3+
1541    3+
1542     3
1543     3
1544    3+
1545    3+
1546     2
1547    3+
1548     2
1549     2
1550     3
1551     3
1552     3
1553    3+
1554    3+
1555    3+
1556     1
1557     1
1558    3+
1559     2
1560    3+
1561    3+
1562     3
1563    3+
1564    3+
1565    3+
1566    3+
1567    3+
1568    3+
1569    3+
1570    3+
1571    3+
1572     3
1573    3+
1574    3+
1575     3
1576    3+
1577     3
1578    3+
1579     3
1580    3+
1581     3
1582     3
1583     3
1584    3+
1585    3+
1586    3+
1587    3+
1588     2
1589     2
1590    3+
1591     2
1592    3+
1593     2
1594     3
1595     3
1596     3
1597     3
1598     1
1599     1
1600     2
1601     3
1602     2
1603     2
1604     2
1605     2
1606     2
1607     2
1608     2
1609    3+
1610    3+
1611     3
1612    3+
1613    3+
1614     3
1615    3+
1616    3+
1617     2
1618     3
1619     2
1620     2
1621    3+
1622     3
1623     3
1624     3
1625     3
1626     3
1627    3+
1628    3+
1629    3+
1630    3+
1631     3
1632    3+
1633     2
1634     2
1635     3
1636     3
1637     3
1638    3+
1639     2
1640     2
1641     3
1642     3
1643    3+
1644     2
1646    3+
1647     2
1648     2
1649     2
1650     3
1651    3+
1652     2
1653     3
1654    3+
1655    3+
1656     2
1657     3
1658     3
1659    3+
1660    3+
1661    3+
1662    3+
1663    3+
1664    3+
1665     3
1666    3+
1667     3
1668     3
1669    3+
1670     3
1671    3+
1672    3+
1673     3
1674    3+
1675    3+
1676     3
1677    3+
1678    3+
1679    3+
1680    3+
1681     3
1682    3+
1683     3
1684     3
1685     2
1686    3+
1687     1
1688     2
1689     2
1690    3+
1691    3+
1692    3+
1693    3+
1694    3+
1695    3+
1696    3+
1697     2
1698    3+
1699     2
1700     2
1701     2
1702    3+
1703    3+
1704     3
1705     3
1706    3+
1707    3+
1708    3+
1709     2
1710     2
1711     1
1712     1
1713     2
1714     1
1715     2
1716     2
1717    3+
1718    3+
1719     1
1720     1
1721     3
1722     3
1723     2
1724     1
1725     2
1726     2
1727     2
1728     2
1729     1
1730     2
1731     2
1732     2
1733     2
1734     3
1735    3+
1736    3+
1737     2
1738     2
1739    3+
1740    3+
1741     2
1742    3+
1743    3+
1744    3+
1745     3
1746    3+
1747    3+
1748    3+
1749    3+
1750     3
1751     2
1752     3
1753    3+
1754    3+
1755    3+
1756    3+
1757    3+
1758     3
1759     3
1760     3
1761     3
1762     2
1763     2
1764     2
1765    3+
1766     1
1767     2
1768    3+
1769     2
1770     2
1771     2
1772     2
1773     2
1774     1
1775    3+
1776     1
1777     1
1778     1
1779     2
1780     2
1781     2
1782     2
1783     3
1784    3+
1785    3+
1786    3+
1787     3
1788    3+
1789    3+
1790    3+
1791     2
1792    3+
1793    3+
1794    3+
1795     2
1796     2
1797     2
1798     2
1799     2
1800     2
1801     2
1802     3
1803     3
1804     3
1805     3
1806     3
1807     2
1808    3+
1809     1
1810     3
1811     3
1812    3+
1813     3
1814     3
1815     2
1816     3
1817     2
1818     2
1819     3
1820     3

In [38]:
## preprocessing additionalRoom 

df['additionalRoom'].value_counts().shape

(49,)

In [39]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

In [40]:
df['additionalRoom'].fillna('not available', inplace=True)

C:\Users\abhay\AppData\Local\Temp\ipykernel_4444\1205007737.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available', inplace=True)

In [41]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [42]:
## Preprocessing floorNum col

df['floorNum'].value_counts().shape

(550,)

In [43]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,No Balcony,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN,G8922001
2767,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,No Balcony,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",T8073153

In [44]:
df['floorNum']=df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [45]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [46]:
## Preprocessing facing 
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [47]:
df['facing'].isnull().sum()

np.int64(874)

In [48]:
df['facing'].fillna('NA', inplace=True)

C:\Users\abhay\AppData\Local\Temp\ipykernel_4444\3102712490.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA', inplace=True)

In [49]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [50]:
df.insert(loc=4, column='area', value= round((df['price']*10000000/df['price_per_sqft'])))

In [51]:
df.insert(loc=1, column = 'property_type', value='flat')

In [52]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [53]:
df.shape

(2997, 21)

In [54]:
df.to_csv('flats_cleaned.csv', index= False)